version: '3.8'

services:
  spot_that_fi:
    container_name: spot_that_fi
    build: .
    environment:
      - SPOTIPY_CLIENT_ID=''
      - SPOTIPY_CLIENT_SECRET=''
    volumes: 
      # - /root/repositories/spot_that_fi/logs:/usr/src/app/logs 
      # - /root/repositories/spot_that_fi/playlist.json:/usr/src/app/playlist.json 
      - /home/huy/repositories/spot_that_fi/logs:/usr/src/app/logs 
      - /home/huy/repositories/spot_that_fi/src/playlist.json:/usr/src/app/playlist.json 
    restart: unless-stopped